# -*- coding: utf-8 -*-
"""EDA on food-order-data- using python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQUucms_odt3Nl0gF4xj-KcauXhSAyQi

## EXPLORATORY DATA ANALYSIS ON FOOD ORDERS - USING PYTHON
"""

import pandas as pd
import seaborn as sns

"""# Data preparation

- involves loading, data inspection , missing value analysis and handling, e.t.c
"""

df = pd.read_csv("food_orders.csv") # loads the csv file to pandas dataframe.

df.head()

df.info()

# split date & time column
df[["~order time", "~order date"]] = df["Order Placed At"].str.split(", ", expand=True)

# glimpse of data

df.head()

numericDf = df.select_dtypes(include= "number")
non_numericDf = df.select_dtypes(include= "object")

# summary statistics -- numeric fields
numericDf.describe().iloc[:, 2:]

non_numericDf.describe().T # summary of non-numeric fields

df.info()

df['~order date'] = pd.to_datetime(df['~order date'])

df['~order time']=  pd.to_timedelta(df['~order time'] + ":00")

df.head()

df.isna().sum().plot(kind="barh", title="Missing Values Plot") # missing value analysis

df["Distance"].value_counts()

# save processed data

#df.to_excel("sample_data/food_orders_clean.xlsx", index=False)



"""# Numeric field plot

- Visualizing numeric fields to discover trends and relationships
"""

df[['KPT duration (minutes)',	'Rider wait time (minutes)']].\
plot(kind="scatter", x='KPT duration (minutes)'	,y= 'Rider wait time (minutes)')

numericDf.head()

numericDf.isna().sum()

df[['Restaurant discount (Promo)', 'Total']].\
plot(kind="scatter", x='KPT duration (minutes)'	,y= 'Rider wait time (minutes)')

df[['Restaurant discount (Promo)', 'Total']].\
plot(kind="scatter", x='Restaurant discount (Promo)'	,y= 'Total')

"""# Categorical fields"""

non_numericDf.head()

non_numericDf['Order Status'].value_counts()

non_numericDf['Order Status'].value_counts().plot(kind='bar')

non_numericDf['Restaurant name'].value_counts()

non_numericDf['Delivery'].value_counts()

non_numericDf['Order Ready Marked'].value_counts()

non_numericDf['Order Ready Marked'].value_counts().plot(kind='pie')

non_numericDf['Distance'].value_counts().plot(kind='bar')

non_numericDf['Cancellation / Rejection reason'].value_counts()

non_numericDf['Cancellation / Rejection reason'].value_counts().plot(kind='pie')

non_numericDf['Customer complaint tag'].value_counts()

non_numericDf['Customer complaint tag'].value_counts().plot(kind='pie')

numericDf.head()

num_df = numericDf[['Bill subtotal', 'Packaging charges',
       'Restaurant discount (Promo)',
       'Restaurant discount (Flat offs, Freebies & others)', 'Gold discount',
       'Brand pack discount', 'Total', 'Rating',
       'Restaurant compensation (Cancellation)',
       'Restaurant penalty (Rejection)']]

num_df.head()

"""# Correlation

- Correlations and heatmap visualization
"""

num_df.corr()

sns.heatmap(num_df.corr(), annot=True)

"""Next,

Load the clean data to Tableau for further data analysis and visualization.
"""

